export const commonLanguages = {
	ar: "Arabic",
	bg: "Bulgarian",
	"bg-BG": "Bulgarian (Bulgaria)",
	bn: "Bengali",
	cs: "	Czech",
	"cs-CZ": "Czech (Czechia)",
	bs: "Bosnian",
	"bs-BA": "Bosnian (Bosnia and Herzegovina)",
	da: "Danish",
	"da-DK": "Danish (Denmark)",
	de: "German",
	"de-AT": "German (Austria)",
	"de-CH": "German (Switzerland)",
	"de-DE": "German (Germany)",
	el: "Greek",
	"el-GR": "Greek (Greece)",
	en: "English",
	"en-AU": "	English (Australia)",
	"en-CA": "English (Canada)",
	"en-GB": "English (Great Britain)",
	"en-IN": "English (India)",
	"en-NZ": "English (New Zealand)",
	"en-SG": "	English (Singapore)",
	"en-US": "	English (United States)",
	es: "Spanish",
	"es-AR": "Spanish (Argentina)",
	"es-ES": "Spanish (Spain)",
	"es-UY": "Spanish (Uruguay)",
	et: "Estonian",
	"et-EE": "Estonian (Estonia)",
	fi: "Finnish",
	fr: "	French",
	"fr-BE": "French (Belgium)",
	"fr-CH": "French (Switzerland)",
	"fr-FR": "French (France)",
	"fi-FI": "Finnish (Finland)",
	"fr-CA": "French (Canada)",
	fy: "Frisian",
	"fy-NL": "	Frisian (Netherlands)",
	hi: "Hindi",
	hr: "Croatian",
	"hr-HR": "Croatian (Croatia)",
	is: "Icelandic",
	"is-IS": "	Icelandic (Iceland)",
	it: "Italian",
	"it-CH": "	Italian (Switzerland)",
	"it-IT": "Italian (Italy)",
	ja: "	Japanese",
	ko: "	Korean",
	lt: "	Lithuanian",
	"lt-LT": "	Lithuanian (Lithuania)",
	lv: "Latvian",
	"lv-LV": "	Latvian (Latvia)",
	nl: "	Dutch",
	"nl-BE": "Dutch (Belgium)",
	"nl-NL": "Dutch (Netherlands)",
	no: "Norwegian",
	"no-NO": "Norwegian (Norway)",
	pa: "Punjabi",
	pl: "Polish",
	"pl-PL": "	Polish (Poland)",
	pt: "Portuguese",
	"pt-PT": "	Portuguese (Portugal)",
	"pt-BR": "Portuguese (Brazil)",
	ro: "Romanian",
	"ro-RO": "Romanian (Romania)",
	ru: "Russian",
	"ru-RU": "	Russian (Russia)",
	sk: "Slovakian",
	"sk-SK": "	Slovakian (Slovakia)",
	sl: "Slovenian",
	"sl-SI": "	Slovenian (Slovenia)",
	sr: "Serbian",
	"sr-RS": "Serbian (Serbia)",
	sv: "Swedish",
	"sv-SE": "Swedish (Sweden)",
	te: "Telugu",
	zh: "Chinese",
	"zh-CN": "Chinese (China)",
	"zh-HK": "	Chinese (Hong Kong)",
	"zh-SG": "Chinese (Singapore)",
	"zh-TW": "Chinese (Taiwan)",
};

/* export const commonLanguages = {
	Arabic: "ar",
	Bulgarian: "bg",
	"Bulgarian (Bulgaria)": "bg-BG",
	Bengali: "bn",
	Czech: "cs",
	"Czech (Czechia)": "cs-CZ",
	Bosnian: "bs",
	"Bosnian (Bosnia and Herzegovina)": "bs-BA",
	Danish: "da",
	"Danish (Denmark)": "da-DK",
	German: "de",
	"German (Austria)": "de-AT",
	"German (Switzerland)": "de-CH",
	"German (Germany)": "de-DE",
	Greek: "el",
	"Greek (Greece)": "el-GR",
	English: "en",
	"English (Australia)": "en-AU",
	"English (Canada)": "en-CA",
	"English (Great Britain)": "en-GB",
	"English (India)": "en-IN",
	"English (New Zealand)": "en-NZ",
	"English (Singapore)": "en-SG",
	"English (United States)": "en-US",
	Spanish: "es",
	"Spanish (Argentina)": "es-AR",
	"Spanish (Spain)": "es-ES",
	"Spanish (Uruguay)": "es-UY",
	Estonian: "et",
	"Estonian (Estonia)": "et-EE",
	Finnish: "fi",
	French: "fr",
	"French (Belgium)": "fr-BE",
	"French (Switzerland)": "fr-CH",
	"French (France)": "fr-FR",
	"Finnish (Finland)": "fi-FI",
	"French (Canada)": "fr-CA",
	Frisian: "fy",
	"Frisian (Netherlands)": "fy-NL",
	Hindi: "hi",
	Croatian: "hr",
	"Croatian (Croatia)": "hr-HR",
	Icelandic: "is",
	"Icelandic (Iceland)": "is-IS",
	Italian: "it",
	"Italian (Switzerland)": "it-CH",
	"Italian (Italy)": "it-IT",
	Japanese: "ja",
	Korean: "ko",
	Lithuanian: "lt",
	"Lithuanian (Lithuania)": "lt-LT",
	Latvian: "lv",
	"Latvian (Latvia)": "lv-LV",
	Dutch: "nl",
	"Dutch (Belgium)": "nl-BE",
	"Dutch (Netherlands)": "nl-NL",
	Norwegian: "no",
	"Norwegian (Norway)": "no-NO",
	Punjabi: "pa",
	Polish: "pl",
	"Polish (Poland)": "pl-PL",
	Portuguese: "pt",
	"Portuguese (Portugal)": "pt-PT",
	"Portuguese (Brazil)": "pt-BR",
	Romanian: "ro",
	"Romanian (Romania)": "ro-RO",
	Russian: "ru",
	"Russian (Russia)": "ru-RU",
	Slovakian: "sk",
	"Slovakian (Slovakia)": "sk-SK",
	Slovenian: "sl",
	"Slovenian (Slovenia)": "sl-SI",
	Serbian: "sr",
	"Serbian (Serbia)": "sr-RS",
	Swedish: "sv",
	"Swedish (Sweden)": "sv-SE",
	Telugu: "te",
	Chinese: "zh",
	"Chinese (China)": "zh-CN",
	"Chinese (Hong Kong)": "zh-HK",
	"Chinese (Singapore)": "zh-SG",
	"Chinese (Taiwan)": "zh-TW",
}; */
