// this file contains all the used valueSets that some elements are bound to.

export const addressUse = ["home", "work", "temp", "old", "billing"];
export const OrganizationAddressUse = ["work", "temp", "old", "billing"];
export const addressType = ["postal", "physical", "both"];
export const genders = ["male", "female", "other", "unknown"];
export const nameUse = [
	"usual",
	"official",
	"temp",
	"nickname",
	"anonymous",
	"old",
	"maiden",
];
export const identifierUse = ["usual", "official", "temp", "secondary", "old"];
export const linkType = ["replaced-by", "replaces", "refer", "seealso"];
export const patientContactRelationship = [
	"BP",
	"C",
	"CP",
	"E",
	"EP",
	"F",
	"I",
	"N",
	"PR",
	"S",
	"U",
];
export const maritalStatus = [
	"A",
	"D",
	"I",
	"L",
	"M",
	"P",
	"S",
	"T",
	"U",
	"W",
	"UNK",
];
export const organizationType = [
	"prov",
	"dept",
	"govt",
	"pay",
	"edu",
	"reli",
	"crs",
	"cg",
	"bus",
	"other",
];
export const contactEntityType = [
	"BILL",
	"ADMIN",
	"HR",
	"PAYOR",
	"PATINF",
	"PRESS",
];
export const contactPointSystem = [
	"phone",
	"fax",
	"email",
	"pager",
	"url",
	"sms",
	"other",
];
export const contactPointUse = ["home", "work", "temp", "old", "mobile"];
export const OrganizationContactPointUse = ["work", "temp", "old", "mobile"];

export const commonLanguages = {
	ar: "Arabic",
	bg: "Bulgarian",
	"bg-BG": "Bulgarian (Bulgaria)",
	bn: "Bengali",
	cs: "	Czech",
	"cs-CZ": "Czech (Czechia)",
	bs: "Bosnian",
	"bs-BA": "Bosnian (Bosnia and Herzegovina)",
	da: "Danish",
	"da-DK": "Danish (Denmark)",
	de: "German",
	"de-AT": "German (Austria)",
	"de-CH": "German (Switzerland)",
	"de-DE": "German (Germany)",
	el: "Greek",
	"el-GR": "Greek (Greece)",
	en: "English",
	"en-AU": "	English (Australia)",
	"en-CA": "English (Canada)",
	"en-GB": "English (Great Britain)",
	"en-IN": "English (India)",
	"en-NZ": "English (New Zealand)",
	"en-SG": "	English (Singapore)",
	"en-US": "	English (United States)",
	es: "Spanish",
	"es-AR": "Spanish (Argentina)",
	"es-ES": "Spanish (Spain)",
	"es-UY": "Spanish (Uruguay)",
	et: "Estonian",
	"et-EE": "Estonian (Estonia)",
	fi: "Finnish",
	fr: "	French",
	"fr-BE": "French (Belgium)",
	"fr-CH": "French (Switzerland)",
	"fr-FR": "French (France)",
	"fi-FI": "Finnish (Finland)",
	"fr-CA": "French (Canada)",
	fy: "Frisian",
	"fy-NL": "	Frisian (Netherlands)",
	hi: "Hindi",
	hr: "Croatian",
	"hr-HR": "Croatian (Croatia)",
	is: "Icelandic",
	"is-IS": "	Icelandic (Iceland)",
	it: "Italian",
	"it-CH": "	Italian (Switzerland)",
	"it-IT": "Italian (Italy)",
	ja: "	Japanese",
	ko: "	Korean",
	lt: "	Lithuanian",
	"lt-LT": "	Lithuanian (Lithuania)",
	lv: "Latvian",
	"lv-LV": "	Latvian (Latvia)",
	nl: "	Dutch",
	"nl-BE": "Dutch (Belgium)",
	"nl-NL": "Dutch (Netherlands)",
	no: "Norwegian",
	"no-NO": "Norwegian (Norway)",
	pa: "Punjabi",
	pl: "Polish",
	"pl-PL": "	Polish (Poland)",
	pt: "Portuguese",
	"pt-PT": "	Portuguese (Portugal)",
	"pt-BR": "Portuguese (Brazil)",
	ro: "Romanian",
	"ro-RO": "Romanian (Romania)",
	ru: "Russian",
	"ru-RU": "	Russian (Russia)",
	sk: "Slovakian",
	"sk-SK": "	Slovakian (Slovakia)",
	sl: "Slovenian",
	"sl-SI": "	Slovenian (Slovenia)",
	sr: "Serbian",
	"sr-RS": "Serbian (Serbia)",
	sv: "Swedish",
	"sv-SE": "Swedish (Sweden)",
	te: "Telugu",
	zh: "Chinese",
	"zh-CN": "Chinese (China)",
	"zh-HK": "	Chinese (Hong Kong)",
	"zh-SG": "Chinese (Singapore)",
	"zh-TW": "Chinese (Taiwan)",
};
